# Generated by Django 3.1.4 on 2021-01-09 20:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_img',
            field=models.ImageField(upload_to=blog.models.imageupload),
        ),
    ]
