# Generated by Django 3.1.4 on 2021-01-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210109_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
